# Generated by Django 5.2.6 on 2025-09-05 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_starship_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starship',
            name='character',
        ),
        migrations.AddField(
            model_name='starship',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='starships', to='app.character'),
        ),
        migrations.AddField(
            model_name='starship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='starship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
