# Generated by Django 5.2.6 on 2025-09-03 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("episode_id", models.IntegerField(blank=True, null=True)),
                ("director", models.CharField(blank=True, max_length=100)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("height", models.FloatField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=50)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "films",
                    models.ManyToManyField(
                        blank=True, related_name="characters", to="app.film"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Starship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=500)),
                ("cost_in_credits", models.BigIntegerField(blank=True, null=True)),
                ("hyperdrive_rating", models.FloatField(blank=True, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starships",
                        to="app.character",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="film",
            name="starships",
            field=models.ManyToManyField(
                blank=True, related_name="films", to="app.starship"
            ),
        ),
    ]
