# Generated by Django 5.2.6 on 2025-09-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='swapi_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='swapi_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='starship',
            name='swapi_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
