# Generated by Django 5.2.6 on 2025-09-05 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_character_swapi_url_film_swapi_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starship',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starships', to='app.character'),
        ),
    ]
