# Generated by Django 5.2.6 on 2025-09-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_starship_character_starship_characters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='swapi_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='The resource id on swapi data', null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='swapi_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='The resource id on swapi data', null=True),
        ),
        migrations.AddField(
            model_name='starship',
            name='swapi_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='The resource id on swapi data', null=True),
        ),
    ]
