# Generated by Django 5.2.6 on 2025-09-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_character_swapi_id_film_swapi_id_starship_swapi_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_type', models.CharField(choices=[('film', 'Film'), ('character', 'Character'), ('starship', 'Starship')], max_length=20)),
                ('from_swapi_id', models.BigIntegerField(db_index=True)),
                ('to_type', models.CharField(choices=[('film', 'Film'), ('character', 'Character'), ('starship', 'Starship')], max_length=20)),
                ('to_swapi_id', models.BigIntegerField(db_index=True)),
            ],
        ),
    ]
