# Generated by Django 5.2.6 on 2025-09-29 09:03

import psqlextra.backend.migrations.operations.add_default_partition
import psqlextra.backend.migrations.operations.create_partitioned_model
import psqlextra.manager.manager
import psqlextra.models.partitioned
import psqlextra.types
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_character_swapi_id_film_swapi_id_starship_swapi_id'),
    ]

    operations = [
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name='StagedRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_type', models.CharField(choices=[('film', 'Film'), ('character', 'Character'), ('starship', 'Starship')], max_length=20)),
                ('from_swapi_id', models.BigIntegerField(db_index=True)),
                ('to_type', models.CharField(choices=[('film', 'Film'), ('character', 'Character'), ('starship', 'Starship')], max_length=20)),
                ('to_swapi_id', models.BigIntegerField(db_index=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            partitioning_options={
                'method': psqlextra.types.PostgresPartitioningMethod['LIST'],
                'key': ['from_type'],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        psqlextra.backend.migrations.operations.add_default_partition.PostgresAddDefaultPartition(
            model_name='StagedRelationship',
            name='default',
        ),
    ]
