# Generated by Django 5.2.6 on 2025-09-29 09:04

from django.db import migrations
from psqlextra.backend.migrations.operations import PostgresAddListPartition
from .. import constants


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_staged_relationship_partitioned'),
    ]

    operations = [
        PostgresAddListPartition(
            model_name="stagedrelationship",
            name="film",
            values=[constants.ResourceEnum.FILM.value],
        ),
        PostgresAddListPartition(
            model_name="stagedrelationship",
            name="character",
            values=[constants.ResourceEnum.CHARACTER.value],
        ),
        PostgresAddListPartition(
            model_name="stagedrelationship",
            name="starship",
            values=[constants.ResourceEnum.STARSHIP.value],
        ),
    ]
