# Generated by Django 5.2.6 on 2025-09-29 09:21

import psqlextra.manager.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_define_partitions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='character',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='film',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='starship',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
