name: Django Test with Coverage
run-name: ${{ github.actor }} is running Django tests with coverage in Docker 🚀
on:
  push:
    branches: [main, dev-docker-ci]
  pull_request:
    branches: [main, dev]

jobs:
  docker-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create CI env file
        run: |
          cat <<EOF > .env
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          POSTGRES_DB=${{ vars.POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST=${{ vars.POSTGRES_HOST }}
          POSTGRES_INTERNAL_PORT=${{ vars.POSTGRES_INTERNAL_PORT }}
          POSTGRES_EXTERNAL_PORT=${{ vars.POSTGRES_EXTERNAL_PORT }}
          BACKEND_INTERNAL_PORT=${{ vars.BACKEND_INTERNAL_PORT }}
          BACKEND_EXTERNAL_PORT=${{ vars.BACKEND_EXTERNAL_PORT }}
          EOF
          echo "Generated .env:"
          cat .env

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose.yaml
          up-flags: "-d"

      - name: Execute tests in the running services
        run: |
          docker compose exec srv-sw-back bash -c "python -m coverage run manage.py test && python -m coverage html"

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/backend/htmlcov
          retention-days: 2